@include('elements.header')
<section id="portfolio" class="portfolio" style="background: white;">
    <div class="container">

        <div class="heading">

            <span>Terms of Use</span>
        </div>
        <!--end heading-->
        <div class="portfoliomain">
        	<div style="background:white; ">
	<div style=" font-align:justify;">
		<p>This website: <a href="http://talenttantra.com/">http://talenttantra.com/</a> (“<strong>Website</strong>”)is ownedand operated by North Eastern Knowledge Foundation, promoters of The Assam Kaziranga University (<strong>“KU</strong>”). Through the Website, KU provides users with information regarding and tickets to KU’s annual fest – Talent Tantra, including without limitation the proposed activities, competitions, participation fees and general rules and regulations surrounding Talent Tantra(“<strong>Services</strong>”).<br><br>
		The terms ‘North Eastern Knowledge Foundation’, ‘Assam Kaziranga University’, ‘KU’ or ‘us’ or ‘we’ refer to the owners of theWebsite and organisers of Talent Tantra. The term ‘you’ refers to the user or viewer of our Website. “Party”, or “Parties”, refers to both you and KU.<br><br>
		By browsing, viewing, using the Website and/or availing the Services provided therein you consent to and agree to comply with these terms and conditions of use (“<strong>Terms</strong>” or “<strong>Terms of Use</strong>”), which together with our Privacy Policy and associated rules, regulations and terms and conditions notified by KU at its sole and absolute discretion, including without limitation rules of participation and ticketing terms, incorporated herein by reference, govern KU’s relationship with you in relation to this Website. If you disagree with any part of these Terms, please discontinue using our Website immediately. KU reserves the right to change or modify the Website, the contents thereof and these Terms of Use at any time without any prior intimation to you. All modifications will be posted on the Website and will become effective immediately upon such posting to the Website. Please review these Terms of Use regularly to remain informed of any change.<br><br>
		ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THESE TERMS, AS MODIFIED FROM TIME TO TIME. THEREFORE, PLEASE READ THESE TERMS CAREFULLY BEFORE PROCEEDING.</p><br><br>
		<p><b>Website Content - </b> KU authorises you, subject to these Terms, to view and access the content available on or from the Website and to access and use the Website and the Content (as defined below) solely for your personal, non-commercial use. The contents of the Website, and of all other websites under KU’s control, whether partial or otherwise, such as designs, text, graphics, images, video, information, logos, button icons, software, audio files and other content (collectively, “<strong>Content</strong>”), are protected under applicable copyright, trademark and other laws. All Content is the property of KU or its licensors. The compilation (meaning the collection, arrangement and assembly) of all content on the Website is the exclusive property of KU and is protected by Indian and international copyright, trademark, and other laws. Unauthorised use of the Content may violate these laws and/or applicable communications regulations and statutes, and is strictly prohibited. You may not sell or modify the Content or reproduce, display, publicly perform, distribute, or otherwise use the Content in any way for any public or commercial purpose, in connection with products or services that are not those of KU, in any other manner that is likely to cause confusion among consumers or that otherwise infringes KU's intellectual property rights. Any use of the Content for which or pursuant to which you receive or intend to receive any remuneration, whether monetary or otherwise, is a commercial use for the purposes of this clause.</p><br>
		<p><b>Contributed Content - </b>This website may contain views/ideas/opinions expressed by independent authors/contributors/posters/users on various topics (“<strong>Content</strong>”). Such views/ideas/opinions are solely those of the authors/contributors/posters/users and not endorsed in any manner by KU. KU shall not be responsible for or liable in any manner whatsoever for the views/ideas/opinions expressed by such authors/contributors/posters/users in any section of this website. Further, the accuracy of such statements has not been verified by KU and KU provides no warranties of the same. If you seek to rely on any representation of information contained on this Website, any such reliance shall be at your own risk.<br>
		You agree and warrant that you will not contribute, post or any upload any Content onto the Website that:&nbsp;<br>
		&emsp;&emsp;1) you do not have any right to or belongs to any other person; or<br>
		&emsp;&emsp;2) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another person’s privacy, hateful, racially or ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or<br>
		&emsp;&emsp;3) harm minors in any way; or<br>
		&emsp;&emsp;4) infringes any patent, trademark, copyright or other proprietary rights; or<br>
		&emsp;&emsp;5) violates any law for the time being in force; or<br>
		&emsp;&emsp;6) deceives or misleads other users of the website about the origin of such messages or communicates any information which is grossly offensive or menacing in nature; or<br>
		&emsp;&emsp;7) impersonates another person; or<br>
		&emsp;&emsp;8) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or<br>
		&emsp;&emsp;9) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states or is insulting to any other nation; or<br>
		&emsp;&emsp;10)threatens public order or causes incitement to the commission of any offences or prevents investigation of any offence by law enforcement authorities.<br>
		</p><br>
		<p><b>User Conduct - </b>You agree and acknowledge that you shall not use the Website in any way that causes, or is likely to cause, the Website, the Services or access to the Website and the Services to be interrupted, damaged or impaired in any manner whatsoever. You understand that you are solely responsible and liable for any communications and content sent by you to us and you shall use the Website for lawful purposes only.<br>
		In particular, you represent and warrant that you will not use the Website and the Services therein for <em>mala fide</em>, commercial, illegal or fraudulent purposes, or in connection with a criminal offense or other unlawful activity and you will not in the course of use of the Website or Services:<br>
		&emsp;&emsp;1) act in an abusive, offensive or intimidating manner;<br>
		&emsp;&emsp;2) cause damage to any third party property or injure any third party;<br>
		&emsp;&emsp;3) impersonate another person or bind a third party to a course of action without such party’s consent; or<br>
		&emsp;&emsp;4) act in an objectionable or otherwise unlawful in any manner whatsoever.<br>
		In the event a user uses a false phone number, violates any of the representations here in above, impersonates any person or entity, or otherwise misleads us as to the authenticity of any information, KU reserves the right (but not the obligation) to terminate such user’s permission to access or use the Website, Service(s) and/or seek any other remedies available under contract or law.</p><br>
		<p><b>Warranty and Liability Disclaimer - </b>
		This Website and the Content herein is provided by KU in good faith on an “as is”, “as available” basis and KU does not guarantee the accuracy, timeliness, completeness, performance or fitness for a particular purpose of this Website. Further, KU makes no representations or warranties of any kind, express or implied, as to the operation of this Website, the information, the Content or materials herein or hereon. To the extent as permitted under applicable law, KU disclaims all responsibility (whether direct, indirect, consequential or otherwise) with respect to the accuracy or otherwise of the information, Content, materials or products arising from the use of this Website. Without prejudice to the foregoing paragraph, KU does not warrant that:<br>
		&emsp;&emsp;1) This Website will be constantly available, or available at all; or<br>
		&emsp;&emsp;2) The information on this Website is complete, true, accurate or not misleading; or<br>
		&emsp;&emsp;3) The quality of any products, services, information regarding any event, procedure for participation or otherwise, or other material that you obtain through the Website will meet your expectations.<br>
		KU, to the fullest extent permitted by law, disclaims all warranties, whether express or implied, including the warranty of fitness for particular purpose and non-infringement. KU makes no warranties about the accuracy, reliability, completeness, or timeliness of any content, software, text, graphics and links.<br>
		KU reserves the right to revise, review, suspend or withdraw any of the Content within this Website, at its sole discretion and at any time without prior notice, including without limitation any events, Services and terms.<br>
		KU does not warrant that this Website; information, Content or materials included on or otherwise made available to you through this Website; the servers hosting the Website; or electronic communication sent from KU are free of viruses or other harmful components. KU utilises safeguards and industry best practices to protect the Website from hackers, sniffers and malicious modification tools, however, it does not warrant that the Website shall be completely safe from such attacks at any period of time.<br>
		Nothing on this Website constitutes, or is meant to constitute, advice of any kind.</p><br>
		<p><u>Third Party Links - </u>
		Please note that this Website may contain links provided by third parties. Any website, information or services accessed by or as a result of following such third party links is at your sole risk. The content viewed through any third party links is not endorsed in any manner by KU. KU shall not be responsible for or liable in any manner whatsoever for the content provided by such third party links. Further, the accuracy of the content provided through third party links has not been verified by KU and we provide no warranties with respect to the same. Any information collected on websites visited through such third party links is subject to the privacy policies of such third party websites.</p><br>
		<p><strong>Accuracy of Information - </strong>
		Information provided herein this Website is accurate at the time of publishing. However, courses, services, infrastructure, faculty and administration and publications remain subject to change. The information presented on this Website has been compiled by KU from various sources including from external sources. No representation is made or warranty given as to the completeness, accuracy, merchantability and/or fitness for a particular purpose of the Content and any other information. This Website may contain typographical errors, incomplete or out of date information. KU reserves the right to make changes to the Content and information on this Website, or to the services described therein, or update such information at any time without notice, but KU makes no commitment to correct or update this information. If you seek to rely on any representation of information contained on this Website, any such reliance shall be at your own risk.</p><br>
		<p><strong>Indemnification - </strong>
		You represent, warrant and covenant (a) that you will fulfil your obligations hereunder these Terms in good faith; (b) that no materials of any kind provided by you will (i) violate, plagiarize, or infringe upon the rights of any third party, including copyright, trademark, privacy or other personal or proprietary rights; or (ii) contain defamatory or otherwise unlawful material. You hereby indemnify, defend and hold harmless KU and all of KU’s officers, directors, owners, agents, information providers, affiliates, licensors, licensees and third party service providers (collectively, the "<strong>Indemnified Parties</strong>") from and against any and all liability and costs, including, without limitation, reasonable legal fees, incurred by the Indemnified Parties in connection with any claim arising out of any breach by you of these Terms or the foregoing representations, warranties and covenants. You shall cooperate as fully as reasonably required in the defense of any such claim. KU reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification by you.</p><br>
		<p><strong>Termination - </strong>
		KU may immediately, without notice, deny you access to this Website if, in KU’s opinion, you fail to comply with any or all of the Terms set forth herein.</p><br>
		<p><strong>Infringement of Copyright - </strong>
		In good faith, if you have reason to believe that any work copyrighted by you has been reproduced, embedded, or linked without any authorization on this Website, in a manner that constitutes an infringement of your copyright under Indian law, please compile the following information and email to: <a href="mailto:anirban@kazirangauniversity.in">anirban@kazirangauniversity.in</a> [<em>RK to confirm</em>]<br>
		&emsp;&emsp;-- A clear identification of the copyrighted work allegedly infringed;<br>
		&emsp;&emsp;-- A clear identification of the allegedly infringing material on the Website (with specific URL reference);<br>
		&emsp;&emsp;-- Your contact details: name, address, e-mail address and phone number;<br>
		&emsp;&emsp;-- A statement that you believe, in good faith, that the use of the copyrighted material allegedly infringed on the Website is not authorized by your agent or the law;<br>
		&emsp;&emsp;-- A statement that the information provided in the notice is accurate, and under penalty of perjury, that the signatory is authorized to act on behalf of the owner of an exclusive copyright right that is allegedly infringed;<br>
		&emsp;&emsp;-- Your signature or a signature of your authorized agent.<br>
		All the contents of this Website and the Content are only for general information or use and are the sole and exclusive property of KU. Except as expressly authorised by KU, no part or portion of the Website and/or the Content therein may be modified, reproduced, republished, uploaded, posted, transmitted, distributed, sold, licensed, rented, publicly displayed or performed, edited, adapted or used to create a derivative work of, in any manner or form.</p><br>
		<p><strong>Applicable Law - </strong>
		This Website, including the Content and information contained herein, shall be governed by the laws of the Republic of India and the courts of Jorhat, India shall retain exclusive jurisdiction to entertain any proceedings in relation to any disputes arising out of the same. As such, the laws of India shall govern any disclaimers, legal notices, privacy policies of this website, and any transactions completed using this Website.</p><br>
		<p><strong>Information Gathered and Tracked - </strong>
		Information submitted through any feedback or questionnaire forms on the Website is stored in a database. Specifically, we may store the name, e-mail address, and certain demographic information (address, occupation, etc.) of the visitors to our Website who wish to interact with KU. Such information will be primarily used to facilitate interaction between users of the Website and KU. We may also use such information to send out occasional promotional materials, including alerts on new services/features offered by KU. We have clearly marked which information is optional and which is mandatory. We guarantee that personal information about users will be used strictly in accordance with our Privacy Policy.</p><br>
		<p><strong>Assignment - </strong>
		You may not assign your rights and obligations under these Terms without the prior written consent of KU. KU may assign its rights and obligations to a third party upon issuing written notification via an announcement on the Website.</p><br>
	</div>
	</div>
        </div>
    </div>
</section>

@include('elements.footerwidget')
@include('elements.footer')